import express from'express';import cors from'cors';import Database from'better-sqlite3';import path from'node:path';import fs from'node:fs';const app=express();app.use(cors());app.use(express.json({limit:'5mb'}));fs.mkdirSync('data',{recursive:true});const db=new Database(path.resolve('data/sats.db'));db.exec(`CREATE TABLE IF NOT EXISTS leads(id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT,company TEXT,phone TEXT,email TEXT,service TEXT,project_type TEXT,location TEXT,description TEXT,status TEXT DEFAULT 'New',source TEXT DEFAULT 'Website',created_at TEXT DEFAULT CURRENT_TIMESTAMP);CREATE TABLE IF NOT EXISTS customers(id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT,company TEXT,phone TEXT,email TEXT,address TEXT,trn TEXT);CREATE TABLE IF NOT EXISTS projects(id INTEGER PRIMARY KEY AUTOINCREMENT,code TEXT UNIQUE,name TEXT,location TEXT,contract_value REAL DEFAULT 0,status TEXT DEFAULT 'Planning',start_date TEXT,end_date TEXT);CREATE TABLE IF NOT EXISTS workers(id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT,phone TEXT,trade TEXT,worker_type TEXT DEFAULT 'Regular',default_rate REAL DEFAULT 0,status TEXT DEFAULT 'Active');CREATE TABLE IF NOT EXISTS expenses(id INTEGER PRIMARY KEY AUTOINCREMENT,description TEXT,category TEXT,amount REAL DEFAULT 0,date TEXT,payment_method TEXT);CREATE TABLE IF NOT EXISTS quotations(id INTEGER PRIMARY KEY AUTOINCREMENT,number TEXT UNIQUE,customer_id INTEGER,project_name TEXT,status TEXT DEFAULT 'Draft',subtotal REAL DEFAULT 0,vat_rate REAL DEFAULT 5,vat REAL DEFAULT 0,total REAL DEFAULT 0);CREATE TABLE IF NOT EXISTS invoices(id INTEGER PRIMARY KEY AUTOINCREMENT,number TEXT UNIQUE,status TEXT DEFAULT 'Draft',subtotal REAL DEFAULT 0,vat_rate REAL DEFAULT 5,vat REAL DEFAULT 0,total REAL DEFAULT 0);CREATE TABLE IF NOT EXISTS payments(id INTEGER PRIMARY KEY AUTOINCREMENT,invoice_id INTEGER,amount REAL DEFAULT 0,date TEXT);CREATE TABLE IF NOT EXISTS worker_entries(id INTEGER PRIMARY KEY AUTOINCREMENT,worker_id INTEGER,project_id INTEGER,date TEXT,days REAL,rate REAL,total REAL,paid INTEGER DEFAULT 0);`);
const all=(s:string)=>db.prepare(s).all();const one=(s:string,...p:any[])=>db.prepare(s).get(...p) as any;const run=(s:string,...p:any[])=>db.prepare(s).run(...p);
for(const [r,t] of [['leads','leads'],['customers','customers'],['projects','projects'],['workers','workers'],['expenses','expenses'],['quotations','quotations'],['invoices','invoices'],['payments','payments']] as const)app.get('/api/'+r,(_,res)=>res.json(all('SELECT * FROM '+t+' ORDER BY id DESC')));
app.get('/api/dashboard',(_,res)=>{const revenue=one('SELECT COALESCE(SUM(amount),0)v FROM payments').v,expenses=one('SELECT COALESCE(SUM(amount),0)v FROM expenses').v,labour=one('SELECT COALESCE(SUM(total),0)v FROM worker_entries').v;res.json({revenue,expenses,labour,estimated_net:revenue-expenses-labour,receivable:one('SELECT COALESCE(SUM(total),0)v FROM invoices').v-revenue,leads:one("SELECT COUNT(*)v FROM leads WHERE status NOT IN ('Won','Lost')").v,active_projects:one("SELECT COUNT(*)v FROM projects WHERE status NOT IN ('Completed','Cancelled')").v,pending_quotes:one("SELECT COUNT(*)v FROM quotations WHERE status IN ('Draft','Sent','Negotiation')").v})});
app.post('/api/leads',(req,res)=>{const x=req.body,r=run('INSERT INTO leads(name,company,phone,email,service,project_type,location,description)VALUES(?,?,?,?,?,?,?,?)',x.name,x.company||'',x.phone||'',x.email||'',x.service||'',x.project_type||'',x.location||'',x.description||'');res.json(one('SELECT * FROM leads WHERE id=?',r.lastInsertRowid))});
app.post('/api/customers',(req,res)=>{const x=req.body,r=run('INSERT INTO customers(name,company,phone,email,address,trn)VALUES(?,?,?,?,?,?)',x.name,x.company||'',x.phone||'',x.email||'',x.address||'',x.trn||'');res.json(one('SELECT * FROM customers WHERE id=?',r.lastInsertRowid))});
app.post('/api/projects',(req,res)=>{const x=req.body,code=x.code||'P-'+Date.now(),r=run('INSERT INTO projects(code,name,location,contract_value,status,start_date,end_date)VALUES(?,?,?,?,?,?,?)',code,x.name,x.location||'',+x.contract_value||0,x.status||'Planning',x.start_date||'',x.end_date||'');res.json(one('SELECT * FROM projects WHERE id=?',r.lastInsertRowid))});
app.post('/api/workers',(req,res)=>{const x=req.body,r=run('INSERT INTO workers(name,phone,trade,worker_type,default_rate)VALUES(?,?,?,?,?)',x.name,x.phone||'',x.trade||'',x.worker_type||'Regular',+x.default_rate||0);res.json(one('SELECT * FROM workers WHERE id=?',r.lastInsertRowid))});
app.post('/api/expenses',(req,res)=>{const x=req.body,r=run('INSERT INTO expenses(description,category,amount,date,payment_method)VALUES(?,?,?,?,?)',x.description||'',x.category||'Other',+x.amount||0,x.date||new Date().toISOString().slice(0,10),x.payment_method||'');res.json(one('SELECT * FROM expenses WHERE id=?',r.lastInsertRowid))});


// PHASE 6 — purchasing, receiving, inventory movements and project material costing
db.exec(\`CREATE TABLE IF NOT EXISTS suppliers(id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT NOT NULL,phone TEXT,email TEXT,address TEXT,trn TEXT,notes TEXT);
CREATE TABLE IF NOT EXISTS purchase_orders(id INTEGER PRIMARY KEY AUTOINCREMENT,number TEXT UNIQUE NOT NULL,supplier_id INTEGER,project_id INTEGER,status TEXT DEFAULT 'Draft',order_date TEXT,expected_date TEXT,subtotal REAL DEFAULT 0,vat_rate REAL DEFAULT 5,vat REAL DEFAULT 0,total REAL DEFAULT 0,notes TEXT);
CREATE TABLE IF NOT EXISTS purchase_order_items(id INTEGER PRIMARY KEY AUTOINCREMENT,purchase_order_id INTEGER NOT NULL,item_id INTEGER,description TEXT NOT NULL,qty REAL DEFAULT 1,unit TEXT DEFAULT 'PCS',rate REAL DEFAULT 0,amount REAL DEFAULT 0);
CREATE TABLE IF NOT EXISTS inventory_items(id INTEGER PRIMARY KEY AUTOINCREMENT,sku TEXT UNIQUE,name TEXT NOT NULL,category TEXT,unit TEXT DEFAULT 'PCS',quantity REAL DEFAULT 0,min_quantity REAL DEFAULT 0,average_cost REAL DEFAULT 0,location TEXT);
CREATE TABLE IF NOT EXISTS inventory_movements(id INTEGER PRIMARY KEY AUTOINCREMENT,item_id INTEGER NOT NULL,type TEXT NOT NULL,qty REAL NOT NULL,unit_cost REAL DEFAULT 0,total_cost REAL DEFAULT 0,date TEXT,reference TEXT,project_id INTEGER,purchase_order_id INTEGER,notes TEXT);
CREATE TABLE IF NOT EXISTS project_materials(id INTEGER PRIMARY KEY AUTOINCREMENT,project_id INTEGER NOT NULL,item_id INTEGER NOT NULL,qty REAL NOT NULL,unit_cost REAL DEFAULT 0,total_cost REAL DEFAULT 0,date TEXT,reference TEXT);
\`);
app.get('/api/suppliers',(_,res)=>res.json(all('SELECT * FROM suppliers ORDER BY id DESC')));
app.post('/api/suppliers',(req,res)=>{const x=req.body,r=run('INSERT INTO suppliers(name,phone,email,address,trn,notes)VALUES(?,?,?,?,?,?)',x.name,x.phone||'',x.email||'',x.address||'',x.trn||'',x.notes||'');res.json(one('SELECT * FROM suppliers WHERE id=?',r.lastInsertRowid))});
app.get('/api/inventory',(_,res)=>res.json(all('SELECT i.*,CASE WHEN i.quantity<=i.min_quantity THEN 1 ELSE 0 END low_stock FROM inventory_items i ORDER BY i.name')));
app.post('/api/inventory',(req,res)=>{const x=req.body,r=run('INSERT INTO inventory_items(sku,name,category,unit,quantity,min_quantity,average_cost,location)VALUES(?,?,?,?,?,?,?,?)',x.sku||'SKU-'+Date.now(),x.name,x.category||'',x.unit||'PCS',+x.quantity||0,+x.min_quantity||0,+x.average_cost||0,x.location||'');res.json(one('SELECT * FROM inventory_items WHERE id=?',r.lastInsertRowid))});
app.get('/api/inventory/:id/movements',(req,res)=>res.json(all('SELECT * FROM inventory_movements WHERE item_id=? ORDER BY id DESC',+req.params.id)));
app.post('/api/inventory/movement',(req,res)=>{const x=req.body,id=+x.item_id,qty=+x.qty||0;if(!id||qty<=0)return res.status(400).json({error:'item_id and positive qty are required'});const item=one('SELECT * FROM inventory_items WHERE id=?',id);if(!item)return res.status(404).json({error:'Inventory item not found'});const isIn=x.type==='IN';if(!isIn&&item.quantity<qty)return res.status(400).json({error:'Insufficient stock'});const cost=+x.unit_cost||+item.average_cost||0;run('INSERT INTO inventory_movements(item_id,type,qty,unit_cost,total_cost,date,reference,project_id,purchase_order_id,notes)VALUES(?,?,?,?,?,?,?,?,?,?)',id,isIn?'IN':'OUT',qty,cost,qty*cost,x.date||new Date().toISOString().slice(0,10),x.reference||'',x.project_id||null,x.purchase_order_id||null,x.notes||'');if(isIn){const nq=item.quantity+qty;const avg=((item.quantity*(item.average_cost||0))+(qty*cost))/nq;run('UPDATE inventory_items SET quantity=?,average_cost=? WHERE id=?',nq,avg,id)}else run('UPDATE inventory_items SET quantity=quantity-? WHERE id=?',qty,id);res.json(one('SELECT * FROM inventory_items WHERE id=?',id))});
app.post('/api/inventory/issue-to-project',(req,res)=>{const x=req.body,id=+x.item_id,project=+x.project_id,qty=+x.qty||0;if(!id||!project||qty<=0)return res.status(400).json({error:'item_id, project_id and positive qty are required'});const item=one('SELECT * FROM inventory_items WHERE id=?',id);if(!item)return res.status(404).json({error:'Inventory item not found'});if(item.quantity<qty)return res.status(400).json({error:'Insufficient stock'});const cost=+item.average_cost||0;const date=x.date||new Date().toISOString().slice(0,10);run('INSERT INTO inventory_movements(item_id,type,qty,unit_cost,total_cost,date,reference,project_id,notes)VALUES(?,?,?,?,?,?,?,?,?)',id,'OUT',qty,cost,qty*cost,date,x.reference||'Project Issue',project,x.notes||'');run('INSERT INTO project_materials(project_id,item_id,qty,unit_cost,total_cost,date,reference)VALUES(?,?,?,?,?,?,?)',project,id,qty,cost,qty*cost,date,x.reference||'Project Issue');run('UPDATE inventory_items SET quantity=quantity-? WHERE id=?',qty,id);res.json({item:one('SELECT * FROM inventory_items WHERE id=?',id),project_material:one('SELECT * FROM project_materials WHERE id=last_insert_rowid()')})});
app.get('/api/projects/:id/materials',(req,res)=>res.json(all('SELECT pm.*,i.sku,i.name,i.unit FROM project_materials pm JOIN inventory_items i ON i.id=pm.item_id WHERE pm.project_id=? ORDER BY pm.id DESC',+req.params.id)));
app.get('/api/projects/:id/material-cost',(req,res)=>{const v=one('SELECT COALESCE(SUM(total_cost),0)v FROM project_materials WHERE project_id=?',+req.params.id).v;res.json({project_id:+req.params.id,material_cost:v})});
app.get('/api/purchase-orders',(_,res)=>res.json(all('SELECT po.*,s.name supplier_name,p.name project_name FROM purchase_orders po LEFT JOIN suppliers s ON s.id=po.supplier_id LEFT JOIN projects p ON p.id=po.project_id ORDER BY po.id DESC')));
app.post('/api/purchase-orders',(req,res)=>{const x=req.body,num=x.number||'PO-'+Date.now(),sub=+x.subtotal||0,vatRate=x.vat_rate==null?5:+x.vat_rate,vat=sub*vatRate/100,total=sub+vat,r=run('INSERT INTO purchase_orders(number,supplier_id,project_id,status,order_date,expected_date,subtotal,vat_rate,vat,total,notes)VALUES(?,?,?,?,?,?,?,?,?,?,?)',num,x.supplier_id||null,x.project_id||null,x.status||'Draft',x.order_date||new Date().toISOString().slice(0,10),x.expected_date||'',sub,vatRate,vat,total,x.notes||'');res.json(one('SELECT * FROM purchase_orders WHERE id=?',r.lastInsertRowid))});
app.post('/api/purchase-orders/:id/items',(req,res)=>{const x=req.body,po=+req.params.id,a=(+x.qty||1)*(+x.rate||0),r=run('INSERT INTO purchase_order_items(purchase_order_id,item_id,description,qty,unit,rate,amount)VALUES(?,?,?,?,?,?,?)',po,x.item_id||null,x.description||'',+x.qty||1,x.unit||'PCS',+x.rate||0,a);const sub=one('SELECT COALESCE(SUM(amount),0)v FROM purchase_order_items WHERE purchase_order_id=?',po).v,q=one('SELECT vat_rate FROM purchase_orders WHERE id=?',po);run('UPDATE purchase_orders SET subtotal=?,vat=?,total=? WHERE id=?',sub,sub*(q?.vat_rate||5)/100,sub*(1+(q?.vat_rate||5)/100),po);res.json(one('SELECT * FROM purchase_order_items WHERE id=?',r.lastInsertRowid))});
app.post('/api/purchase-orders/:id/receive',(req,res)=>{const poId=+req.params.id,items=all('SELECT * FROM purchase_order_items WHERE purchase_order_id=?',poId);if(!items.length)return res.status(400).json({error:'Purchase order has no items'});for(const x of items){if(!x.item_id)continue;const item=one('SELECT * FROM inventory_items WHERE id=?',x.item_id);if(!item)continue;const nq=item.quantity+x.qty,avg=((item.quantity*(item.average_cost||0))+(x.qty*x.rate))/nq;run('UPDATE inventory_items SET quantity=?,average_cost=? WHERE id=?',nq,avg,x.item_id);run('INSERT INTO inventory_movements(item_id,type,qty,unit_cost,total_cost,date,reference,purchase_order_id)VALUES(?,?,?,?,?,?,?)',x.item_id,'IN',x.qty,x.rate,x.amount,new Date().toISOString().slice(0,10),poId.toString(),poId)}run("UPDATE purchase_orders SET status='Received' WHERE id=?",poId);res.json({purchase_order:one('SELECT * FROM purchase_orders WHERE id=?',poId),received_items:items.length})});
app.get('/api/suppliers/:id/balance',(req,res)=>{const id=+req.params.id,purchased=one('SELECT COALESCE(SUM(total),0)v FROM purchase_orders WHERE supplier_id=? AND status<>"Cancelled"',id).v,paid=one('SELECT COALESCE(SUM(amount),0)v FROM supplier_payments WHERE supplier_id=?',id).v;res.json({supplier_id:id,purchased,paid,balance:purchased-paid})});
app.post('/api/supplier-payments',(req,res)=>{const x=req.body,r=run('INSERT INTO supplier_payments(supplier_id,amount,date,reference)VALUES(?,?,?,?)',+x.supplier_id,+x.amount||0,x.date||new Date().toISOString().slice(0,10),x.reference||'');res.json(one('SELECT * FROM supplier_payments WHERE id=?',r.lastInsertRowid))});

app.listen(4000,()=>console.log('SATS API on http://localhost:4000'));